server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/113908-RICHARD/MultiServices-Springboot
          search-paths: config-data
  application:
    name: config-service
